//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshelf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookshelf.Properties.Resource.Localization", typeof(Resource_Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give.
        /// </summary>
        internal static string btnGiveBook {
            get {
                return ResourceManager.GetString("btnGiveBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add book.
        /// </summary>
        internal static string btnPageBookAdd {
            get {
                return ResourceManager.GetString("btnPageBookAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book.
        /// </summary>
        internal static string btnPageBookEdit {
            get {
                return ResourceManager.GetString("btnPageBookEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give book.
        /// </summary>
        internal static string btnPageBookGive {
            get {
                return ResourceManager.GetString("btnPageBookGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove book.
        /// </summary>
        internal static string btnPageBookRemove {
            get {
                return ResourceManager.GetString("btnPageBookRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search book.
        /// </summary>
        internal static string btnPageBookSearch {
            get {
                return ResourceManager.GetString("btnPageBookSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take book.
        /// </summary>
        internal static string btnPageBookTake {
            get {
                return ResourceManager.GetString("btnPageBookTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        internal static string btnPageHome {
            get {
                return ResourceManager.GetString("btnPageHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string btnPageReport {
            get {
                return ResourceManager.GetString("btnPageReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        internal static string btnPageUserAdd {
            get {
                return ResourceManager.GetString("btnPageUserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string btnPageUserEdit {
            get {
                return ResourceManager.GetString("btnPageUserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user.
        /// </summary>
        internal static string btnPageUserRemove {
            get {
                return ResourceManager.GetString("btnPageUserRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search user.
        /// </summary>
        internal static string btnPageUserSearch {
            get {
                return ResourceManager.GetString("btnPageUserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string btnSignIn {
            get {
                return ResourceManager.GetString("btnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string btnSignUp {
            get {
                return ResourceManager.GetString("btnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take book.
        /// </summary>
        internal static string btnTakeBook {
            get {
                return ResourceManager.GetString("btnTakeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect..
        /// </summary>
        internal static string ErrorIncorrectCredentials {
            get {
                return ResourceManager.GetString("ErrorIncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string GenreEducation {
            get {
                return ResourceManager.GetString("GenreEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string GenreHistory {
            get {
                return ResourceManager.GetString("GenreHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobby.
        /// </summary>
        internal static string GenreHobby {
            get {
                return ResourceManager.GetString("GenreHobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literature.
        /// </summary>
        internal static string GenreLiterature {
            get {
                return ResourceManager.GetString("GenreLiterature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string GenreOther {
            get {
                return ResourceManager.GetString("GenreOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philosophy.
        /// </summary>
        internal static string GenrePhilosophy {
            get {
                return ResourceManager.GetString("GenrePhilosophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politics.
        /// </summary>
        internal static string GenrePolitics {
            get {
                return ResourceManager.GetString("GenrePolitics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychology.
        /// </summary>
        internal static string GenrePsychology {
            get {
                return ResourceManager.GetString("GenrePsychology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string LanguageTurkish {
            get {
                return ResourceManager.GetString("LanguageTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed.
        /// </summary>
        internal static string lblBorrowed {
            get {
                return ResourceManager.GetString("lblBorrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string lblDays {
            get {
                return ResourceManager.GetString("lblDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string lblDueDate {
            get {
                return ResourceManager.GetString("lblDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string lblGenre {
            get {
                return ResourceManager.GetString("lblGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued at.
        /// </summary>
        internal static string lblIssuedAt {
            get {
                return ResourceManager.GetString("lblIssuedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        internal static string lblReturned {
            get {
                return ResourceManager.GetString("lblReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned at.
        /// </summary>
        internal static string lblReturnedAt {
            get {
                return ResourceManager.GetString("lblReturnedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string lblSignInTitle {
            get {
                return ResourceManager.GetString("lblSignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string lblSignUpTitle {
            get {
                return ResourceManager.GetString("lblSignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to sign in.
        /// </summary>
        internal static string lnkSignIn {
            get {
                return ResourceManager.GetString("lnkSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to create a new account.
        /// </summary>
        internal static string lnkSignUp {
            get {
                return ResourceManager.GetString("lnkSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to continue without an account.
        /// </summary>
        internal static string lnkVisitor {
            get {
                return ResourceManager.GetString("lnkVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string RoleAdmin {
            get {
                return ResourceManager.GetString("RoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string RoleNone {
            get {
                return ResourceManager.GetString("RoleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string RoleStaff {
            get {
                return ResourceManager.GetString("RoleStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        internal static string RoleVisitor {
            get {
                return ResourceManager.GetString("RoleVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string TitleAdmin {
            get {
                return ResourceManager.GetString("TitleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookshelf.
        /// </summary>
        internal static string TitleApp {
            get {
                return ResourceManager.GetString("TitleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string TitleSignIn {
            get {
                return ResourceManager.GetString("TitleSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string TitleSignUp {
            get {
                return ResourceManager.GetString("TitleSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string TitleStaff {
            get {
                return ResourceManager.GetString("TitleStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string TitleUser {
            get {
                return ResourceManager.GetString("TitleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        internal static string TitleVisitor {
            get {
                return ResourceManager.GetString("TitleVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string txtAddress {
            get {
                return ResourceManager.GetString("txtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string txtAuthor {
            get {
                return ResourceManager.GetString("txtAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book id.
        /// </summary>
        internal static string txtBookId {
            get {
                return ResourceManager.GetString("txtBookId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue id.
        /// </summary>
        internal static string txtBookIssueId {
            get {
                return ResourceManager.GetString("txtBookIssueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book name.
        /// </summary>
        internal static string txtBookName {
            get {
                return ResourceManager.GetString("txtBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book id, book name, author.
        /// </summary>
        internal static string txtBookSearch {
            get {
                return ResourceManager.GetString("txtBookSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        internal static string txtEdition {
            get {
                return ResourceManager.GetString("txtEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string txtFirstName {
            get {
                return ResourceManager.GetString("txtFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer id.
        /// </summary>
        internal static string txtIssuerId {
            get {
                return ResourceManager.GetString("txtIssuerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer username.
        /// </summary>
        internal static string txtIssuerUsername {
            get {
                return ResourceManager.GetString("txtIssuerUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string txtLastName {
            get {
                return ResourceManager.GetString("txtLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string txtPages {
            get {
                return ResourceManager.GetString("txtPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string txtPhone {
            get {
                return ResourceManager.GetString("txtPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published at.
        /// </summary>
        internal static string txtPublishedAt {
            get {
                return ResourceManager.GetString("txtPublishedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver id.
        /// </summary>
        internal static string txtReceiverId {
            get {
                return ResourceManager.GetString("txtReceiverId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver username.
        /// </summary>
        internal static string txtReceiverUsername {
            get {
                return ResourceManager.GetString("txtReceiverUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        internal static string txtUserId {
            get {
                return ResourceManager.GetString("txtUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string txtUsername {
            get {
                return ResourceManager.GetString("txtUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id, username, email.
        /// </summary>
        internal static string txtUserSearch {
            get {
                return ResourceManager.GetString("txtUserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string WordAdd {
            get {
                return ResourceManager.GetString("WordAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string WordEdit {
            get {
                return ResourceManager.GetString("WordEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string WordRemove {
            get {
                return ResourceManager.GetString("WordRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string WordSearch {
            get {
                return ResourceManager.GetString("WordSearch", resourceCulture);
            }
        }
    }
}
